# single-host configuration for testing purposes
services:
  web:
    build: .
    ports:
      - "8082:8082"
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pswd1
