[package]
name = "frontend-server"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
actix-files = "0.6.0"
#actix-web-httpauth = "0.6.0"

mime = "0.3.16"
sailfish = "0.4.0"
serde = { version = "1.0.82", features = ["derive"]}
serde_json = "1.0.82"
